"""Script generator — converts pointer chain analysis into CE Lua / Python / C++ code."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Literal

ScriptFormat = Literal["ce_lua", "python", "cpp"]


@dataclass
class PointerChain:
    """Represents a resolved pointer chain ready for code generation."""

    base_module: str
    base_offset: int
    offsets: list[int]
    value_type: str = "int"  # int, float, string, pointer
    description: str = ""


@dataclass
class ScriptOutput:
    format: ScriptFormat
    code: str
    chains: list[PointerChain] = field(default_factory=list)


_CE_LUA_TEMPLATE = """-- Auto-generated by game-reai
-- 基址: {base_module}+{base_offset:#x}
-- 偏移链: {offsets_str}
-- 值类型: {value_type}

local base = getAddress("{base_module}+{base_offset_str}")
local p1 = readPointer(base)
if p1 then
{p1_block}
end
"""

_PYMEM_TEMPLATE = '''"""Auto-generated by game-reai."""
import pymem

pm = pymem.Pymem("{process_name}")

{module_base_var} = pm.process_base.lpBaseOfDll
# or: module = pymem.process.module_from_name(pm.process_handle, "{base_module}")
# base = module.lpBaseOfDll

{read_block}
print(f"Value: {{value}}")
'''


class ScriptGenerator:
    """Generate scripts from PointerChain analysis results."""

    def generate_ce_lua(self, chain: PointerChain) -> str:
        offsets_str = " -> ".join(f"0x{o:x}" for o in chain.offsets)
        base_offset_str = f"{chain.base_offset:X}"

        if len(chain.offsets) < 2:
            return self._simple_read_lua(chain)

        read_func = self._ce_read_func(chain.value_type)
        ce_fmt = self._ce_format(chain.value_type)
        n = len(chain.offsets)

        ptr_vars = ["p1"]
        body_lines = [
            "  p1 = readPointer(base)",
            "  if p1 then",
        ]
        indent = "    "

        # Generate p2..pN using offsets[0..N-2]
        for i in range(n - 1):
            prev = ptr_vars[i]
            var = f"p{i + 2}"
            ptr_vars.append(var)
            offset = chain.offsets[i]
            body_lines.append(f"{indent}{var} = readPointer({prev} + {offset:#x})")
            body_lines.append(f"{indent}if {var} then")
            indent += "  "

        # Final value read at last offset
        last_var = ptr_vars[-1]
        last_offset = chain.offsets[-1]
        body_lines.append(f"{indent}local value = read{read_func}({last_var} + {last_offset:#x})")
        body_lines.append(f'{indent}print(string.format("Value: %{ce_fmt}", value))')

        # Close if blocks (in reverse order)
        for _ in range(len(ptr_vars)):
            indent = indent[:-2]
            body_lines.append(f"{indent}end")

        p1_block = "\n".join(body_lines)

        return f"""-- Auto-generated by game-reai
-- 基址: {chain.base_module}+{chain.base_offset:#x}
-- 偏移链: {offsets_str}
-- 值类型: {chain.value_type}

local base = getAddress("{chain.base_module}+{base_offset_str}")
{p1_block}
"""

    def _simple_read_lua(self, chain: PointerChain) -> str:
        """Single-offset or no-offset read."""
        if not chain.offsets:
            return f"""-- 直接读取
local base = getAddress("{chain.base_module}+{chain.base_offset:X}")
local value = read{self._ce_read_func(chain.value_type)}(base)
print(value)
"""
        offset = chain.offsets[0]
        return f"""-- 单级偏移
local base = getAddress("{chain.base_module}+{chain.base_offset:X}")
local p1 = readPointer(base)
if p1 then
  local value = read{self._ce_read_func(chain.value_type)}(p1 + {offset:#x})
  print(value)
end
"""

    def generate(self, chains: list[PointerChain], fmt: ScriptFormat = "ce_lua") -> ScriptOutput:
        code_parts = []
        for c in chains:
            if fmt == "ce_lua":
                code_parts.append(self.generate_ce_lua(c))
            elif fmt == "python":
                code_parts.append(self.generate_python(c))
            elif fmt == "cpp":
                code_parts.append(self.generate_cpp(c))

        return ScriptOutput(
            format=fmt,
            code="\n".join(code_parts),
            chains=chains,
        )

    def generate_python(self, chain: PointerChain, process_name: str = "game.exe") -> str:
        """Generate pymem-based Python script."""
        offsets = chain.offsets
        ptr_names = ["base_ptr"] + [f"ptr{i}" for i in range(1, len(offsets))]

        lines = [
            '"""Auto-generated by game-reai."""',
            "import pymem",
            "",
            f'pm = pymem.Pymem("{process_name}")',
            f'module = pymem.process.module_from_name(pm.process_handle, "{chain.base_module}")',
            "base = module.lpBaseOfDll",
            "",
        ]

        prev = "base"
        for i, offset in enumerate(offsets[:-1]):
            lines.append(f"{ptr_names[i]} = pm.read_longlong({prev} + {offset:#x})")
            lines.append(f"if {ptr_names[i]} == 0:")
            lines.append(f'    raise RuntimeError("指针链断裂在 offset {offset:#x}")')
            lines.append("")
            prev = ptr_names[i]

        if offsets:
            last_offset = offsets[-1]
            lines.append(f"value = pm.read_int({prev} + {last_offset:#x})")
        else:
            lines.append("# 直接读取")
            lines.append("value = pm.read_int(base)")

        lines.append('print(f"Value: {value}")')
        return "\n".join(lines)

    def generate_cpp(self, chain: PointerChain) -> str:
        """Generate Win32 ReadProcessMemory-based C++ code."""
        offsets = chain.offsets
        ptr_names = ["basePtr"] + [f"ptr{i}" for i in range(1, len(offsets))]

        lines = [
            "// Auto-generated by game-reai",
            "#include <windows.h>",
            "#include <iostream>",
            "",
            f"// 基址: {chain.base_module}+{chain.base_offset:#x}",
            f"// 偏移链: {' -> '.join('0x{o:x}' for o in offsets)}",
            "",
            "int main() {",
            "    HANDLE hProcess = OpenProcess(PROCESS_VM_READ, FALSE, <PID>);",
            "    if (!hProcess) return 1;",
            "",
            f"    uintptr_t base = <{chain.base_module}_base> + {chain.base_offset:#x};",
            "",
        ]

        prev = "base"
        for i, offset in enumerate(offsets[:-1]):
            lines.append(f"    uintptr_t {ptr_names[i]};")
            lines.append(f"    ReadProcessMemory(hProcess, (LPCVOID)({prev} + {offset:#x}),")
            lines.append(f"                      &{ptr_names[i]}, sizeof(uintptr_t), NULL);")
            lines.append(f"    if ({ptr_names[i]} == 0) {{")
            lines.append('        std::cerr << "指针链断裂" << std::endl;')
            lines.append("        return 1;")
            lines.append("    }")
            lines.append("")
            prev = ptr_names[i]

        last_offset = offsets[-1] if offsets else 0
        read_type = "int" if chain.value_type in ("int", "4 Bytes") else chain.value_type
        lines.append(f"    {read_type} value;")
        lines.append(f"    ReadProcessMemory(hProcess, (LPCVOID)({prev} + {last_offset:#x}),")
        lines.append("                      &value, sizeof(value), NULL);")
        lines.append('    std::cout << "Value: " << value << std::endl;')
        lines.append("")
        lines.append("    CloseHandle(hProcess);")
        lines.append("    return 0;")
        lines.append("}")

        return "\n".join(lines)

    def _ce_read_func(self, value_type: str) -> str:
        type_map = {
            "int": "Integer",
            "4 Bytes": "Integer",
            "float": "Float",
            "Float": "Float",
            "string": "String",
            "String": "String",
            "pointer": "Pointer",
            "8 Bytes": "Qword",
            "2 Bytes": "SmallInteger",
            "1 Byte": "Byte",
            "bytes": "Bytes",
            "double": "Double",
            "Double": "Double",
        }
        return type_map.get(value_type, "Integer")

    def _ce_format(self, value_type: str) -> str:
        if value_type in ("float", "Float", "double", "Double"):
            return "f"
        if value_type == "pointer":
            return "x"
        return "d"
